from cardinal_sdk.api.KeywordApi import KeywordApi
from cardinal_sdk.api.DeviceApi import DeviceApi
from cardinal_sdk.api.AccessLogBasicApi import AccessLogBasicApi
from cardinal_sdk.api.PlaceApi import PlaceApi
from cardinal_sdk.api.MedicalLocationApi import MedicalLocationApi
from cardinal_sdk.api.TimeTableApi import TimeTableApi
from cardinal_sdk.api.DocumentBasicApi import DocumentBasicApi
from cardinal_sdk.api.PatientBasicApi import PatientBasicApi
from cardinal_sdk.api.TimeTableBasicApi import TimeTableBasicApi
from cardinal_sdk.api.ClassificationApi import ClassificationApi
from cardinal_sdk.api.CalendarItemBasicApi import CalendarItemBasicApi
from cardinal_sdk.api.MaintenanceTaskApi import MaintenanceTaskApi
from cardinal_sdk.api.FormBasicApi import FormBasicApi
from cardinal_sdk.api.RecoveryApi import RecoveryApi
from cardinal_sdk.api.PatientApi import PatientApi
from cardinal_sdk.api.MaintenanceTaskBasicApi import MaintenanceTaskBasicApi
from cardinal_sdk.api.TarificationApi import TarificationApi
from cardinal_sdk.api.ContactApi import ContactApi
from cardinal_sdk.api.ReceiptApi import ReceiptApi
from cardinal_sdk.api.HealthcarePartyApi import HealthcarePartyApi
from cardinal_sdk.api.AccessLogApi import AccessLogApi
from cardinal_sdk.api.PermissionApi import PermissionApi
from cardinal_sdk.api.CodeApi import CodeApi
from cardinal_sdk.api.FrontEndMigrationApi import FrontEndMigrationApi
from cardinal_sdk.api.TopicApi import TopicApi
from cardinal_sdk.api.DocumentTemplateApi import DocumentTemplateApi
from cardinal_sdk.api.HealthElementBasicApi import HealthElementBasicApi
from cardinal_sdk.api.SystemApi import SystemApi
from cardinal_sdk.api.ContactBasicApi import ContactBasicApi
from cardinal_sdk.api.CalendarItemApi import CalendarItemApi
from cardinal_sdk.api.ApplicationSettingsApi import ApplicationSettingsApi
from cardinal_sdk.api.CryptoApi import CryptoApi
from cardinal_sdk.api.ReceiptBasicApi import ReceiptBasicApi
from cardinal_sdk.api.EntityReferenceApi import EntityReferenceApi
from cardinal_sdk.api.ClassificationBasicApi import ClassificationBasicApi
from cardinal_sdk.api.ShamirKeysManagerApi import ShamirKeysManagerApi
from cardinal_sdk.api.DocumentApi import DocumentApi
from cardinal_sdk.api.EntityTemplateApi import EntityTemplateApi
from cardinal_sdk.api.DataOwnerApi import DataOwnerApi
from cardinal_sdk.api.UserApi import UserApi
from cardinal_sdk.api.RoleApi import RoleApi
from cardinal_sdk.api.MessageBasicApi import MessageBasicApi
from cardinal_sdk.api.FormApi import FormApi
from cardinal_sdk.api.InvoiceApi import InvoiceApi
from cardinal_sdk.api.MessageApi import MessageApi
from cardinal_sdk.api.HealthElementApi import HealthElementApi
from cardinal_sdk.api.InvoiceBasicApi import InvoiceBasicApi
from cardinal_sdk.api.TopicBasicApi import TopicBasicApi
from cardinal_sdk.api.InsuranceApi import InsuranceApi
from cardinal_sdk.api.AgendaApi import AgendaApi
from cardinal_sdk.api.GroupApi import GroupApi
