from api.KeywordApi import KeywordApi
from api.DeviceApi import DeviceApi
from api.crypto.ShamirKeysManagerApi import ShamirKeysManagerApi
from api.PlaceApi import PlaceApi
from api.RecoveryApi import RecoveryApi
from api.TarificationApi import TarificationApi
from api.HealthcarePartyApi import HealthcarePartyApi
from api.PermissionApi import PermissionApi
from api.CodeApi import CodeApi
from api.FrontEndMigrationApi import FrontEndMigrationApi
from api.DocumentTemplateApi import DocumentTemplateApi
from api.ApplicationSettingsApi import ApplicationSettingsApi
from api.CryptoApi import CryptoApi
from api.EntityReferenceApi import EntityReferenceApi
from api.EntityTemplateApi import EntityTemplateApi
from api.UserApi import UserApi
from api.RoleApi import RoleApi
from api.extended.IcureMaintenanceTaskApi import IcureMaintenanceTaskApi
from api.extended.DataOwnerApi import DataOwnerApi
from api.ICureApi import ICureApi
from api.flavoured.AccessLogBasicApi import AccessLogBasicApi
from api.flavoured.TimeTableApi import TimeTableApi
from api.flavoured.DocumentBasicApi import DocumentBasicApi
from api.flavoured.PatientBasicApi import PatientBasicApi
from api.flavoured.TimeTableBasicApi import TimeTableBasicApi
from api.flavoured.ClassificationApi import ClassificationApi
from api.flavoured.CalendarItemBasicApi import CalendarItemBasicApi
from api.flavoured.MaintenanceTaskApi import MaintenanceTaskApi
from api.flavoured.FormBasicApi import FormBasicApi
from api.flavoured.PatientApi import PatientApi
from api.flavoured.MaintenanceTaskBasicApi import MaintenanceTaskBasicApi
from api.flavoured.HealthcareElementBasicApi import HealthcareElementBasicApi
from api.flavoured.ContactApi import ContactApi
from api.flavoured.ReceiptApi import ReceiptApi
from api.flavoured.HealthcareElementApi import HealthcareElementApi
from api.flavoured.AccessLogApi import AccessLogApi
from api.flavoured.TopicApi import TopicApi
from api.flavoured.ContactBasicApi import ContactBasicApi
from api.flavoured.CalendarItemApi import CalendarItemApi
from api.flavoured.ReceiptBasicApi import ReceiptBasicApi
from api.flavoured.ClassificationBasicApi import ClassificationBasicApi
from api.flavoured.DocumentApi import DocumentApi
from api.flavoured.MessageBasicApi import MessageBasicApi
from api.flavoured.FormApi import FormApi
from api.flavoured.InvoiceApi import InvoiceApi
from api.flavoured.MessageApi import MessageApi
from api.flavoured.InvoiceBasicApi import InvoiceBasicApi
from api.flavoured.TopicBasicApi import TopicBasicApi
from api.InsuranceApi import InsuranceApi
from api.GroupApi import GroupApi
