package com.icure.sdk.model.base

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class CodeFlag() {
  @SerialName("male_only")
  MaleOnly,
  @SerialName("female_only")
  FemaleOnly,
  @SerialName("deptkinesitherapy")
  Deptkinesitherapy,
  @SerialName("deptnursing")
  Deptnursing,
  @SerialName("deptgeneralpractice")
  Deptgeneralpractice,
  @SerialName("deptsocialworker")
  Deptsocialworker,
  @SerialName("deptpsychology")
  Deptpsychology,
  @SerialName("deptadministrative")
  Deptadministrative,
  @SerialName("deptdietetics")
  Deptdietetics,
  @SerialName("deptspeechtherapy")
  Deptspeechtherapy,
  @SerialName("deptdentistry")
  Deptdentistry,
  @SerialName("deptoccupationaltherapy")
  Deptoccupationaltherapy,
  @SerialName("depthealthcare")
  Depthealthcare,
  @SerialName("deptgynecology")
  Deptgynecology,
  @SerialName("deptpediatry")
  Deptpediatry,
  @SerialName("deptalgology")
  Deptalgology,
  @SerialName("deptanatomopathology")
  Deptanatomopathology,
  @SerialName("deptanesthesiology")
  Deptanesthesiology,
  @SerialName("deptbacteriology")
  Deptbacteriology,
  @SerialName("deptcardiacsurgery")
  Deptcardiacsurgery,
  @SerialName("deptcardiology")
  Deptcardiology,
  @SerialName("deptchildandadolescentpsychiatry")
  Deptchildandadolescentpsychiatry,
  @SerialName("deptdermatology")
  Deptdermatology,
  @SerialName("deptdiabetology")
  Deptdiabetology,
  @SerialName("deptemergency")
  Deptemergency,
  @SerialName("deptendocrinology")
  Deptendocrinology,
  @SerialName("deptgastroenterology")
  Deptgastroenterology,
  @SerialName("deptgenetics")
  Deptgenetics,
  @SerialName("deptgeriatry")
  Deptgeriatry,
  @SerialName("depthandsurgery")
  Depthandsurgery,
  @SerialName("depthematology")
  Depthematology,
  @SerialName("deptinfectiousdisease")
  Deptinfectiousdisease,
  @SerialName("deptintensivecare")
  Deptintensivecare,
  @SerialName("deptlaboratory")
  Deptlaboratory,
  @SerialName("deptmajorburns")
  Deptmajorburns,
  @SerialName("deptmaxillofacialsurgery")
  Deptmaxillofacialsurgery,
  @SerialName("deptmedicine")
  Deptmedicine,
  @SerialName("deptmolecularbiology")
  Deptmolecularbiology,
  @SerialName("deptneonatalogy")
  Deptneonatalogy,
  @SerialName("deptnephrology")
  Deptnephrology,
  @SerialName("deptneurology")
  Deptneurology,
  @SerialName("deptneurosurgery")
  Deptneurosurgery,
  @SerialName("deptnte")
  Deptnte,
  @SerialName("deptnuclear")
  Deptnuclear,
  @SerialName("deptnutritiondietetics")
  Deptnutritiondietetics,
  @SerialName("deptobstetrics")
  Deptobstetrics,
  @SerialName("deptoncology")
  Deptoncology,
  @SerialName("deptophtalmology")
  Deptophtalmology,
  @SerialName("deptorthopedy")
  Deptorthopedy,
  @SerialName("deptpalliativecare")
  Deptpalliativecare,
  @SerialName("deptpediatricintensivecare")
  Deptpediatricintensivecare,
  @SerialName("deptpediatricsurgery")
  Deptpediatricsurgery,
  @SerialName("deptpharmacy")
  Deptpharmacy,
  @SerialName("deptphysicalmedecine")
  Deptphysicalmedecine,
  @SerialName("deptphysiotherapy")
  Deptphysiotherapy,
  @SerialName("deptplasticandreparatorysurgery")
  Deptplasticandreparatorysurgery,
  @SerialName("deptpneumology")
  Deptpneumology,
  @SerialName("deptpodiatry")
  Deptpodiatry,
  @SerialName("deptpsychiatry")
  Deptpsychiatry,
  @SerialName("deptradiology")
  Deptradiology,
  @SerialName("deptradiotherapy")
  Deptradiotherapy,
  @SerialName("deptrevalidation")
  Deptrevalidation,
  @SerialName("deptrheumatology")
  Deptrheumatology,
  @SerialName("deptrhumatology")
  Deptrhumatology,
  @SerialName("deptsenology")
  Deptsenology,
  @SerialName("deptsocialservice")
  Deptsocialservice,
  @SerialName("deptsportsmedecine")
  Deptsportsmedecine,
  @SerialName("deptstomatology")
  Deptstomatology,
  @SerialName("deptsurgery")
  Deptsurgery,
  @SerialName("deptthoracicsurgery")
  Deptthoracicsurgery,
  @SerialName("depttoxicology")
  Depttoxicology,
  @SerialName("depttropicalmedecine")
  Depttropicalmedecine,
  @SerialName("depturology")
  Depturology,
  @SerialName("deptvascularsurgery")
  Deptvascularsurgery,
  @SerialName("deptvisceraldigestiveabdominalsurgery")
  Deptvisceraldigestiveabdominalsurgery,
  @SerialName("depttransplantsurgery")
  Depttransplantsurgery,
  @SerialName("deptpercutaneous")
  Deptpercutaneous,
  @SerialName("deptchildbirth")
  Deptchildbirth,
}
