plugins {
	kotlinMultiplatform()
	kotlinSerialization()
}

val version: String? by project
project.version = version ?: "0.0.0-snapshot"

kotlin {
	val sharedLibBaseName = "cardinal-sdk-native-pylib"
	configureKotlinLinux(this).forEach {
		it.binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}
	macosArm64 {
		binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}
	macosX64 {
		binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}
	mingwX64 {
		binaries {
			sharedLib {
				baseName = sharedLibBaseName
			}
		}
	}

	sourceSets {
		commonMain {
			dependencies {
				implementation(project(":icure-sdk"))
				implementation(libs.coroutinesCore)
			}
		}
	}
}


tasks.register("clearAutoGenerated") {
	doLast {
		projectDir.resolve("src").walkBottomUp().forEach {
			if (
				it.isFile && (
					it.readLines().firstOrNull()?.startsWith("// auto-generated file") == true ||
					it.readLines().firstOrNull()?.startsWith("# auto-generated file") == true
				)
			) {
				it.delete()
			} else if (it.isDirectory && it.listFiles()!!.isEmpty()) {
				it.delete()
			}
		}
	}
}